DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS contact;

CREATE TABLE book (
	id IDENTITY NOT NULL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	author VARCHAR(100) NOT NULL
);

CREATE TABLE contact (
	id IDENTITY NOT NULL PRIMARY KEY,
	name VARCHAR(20) NOT NULL,
	email VARCHAR(100) NOT NULL,
	message VARCHAR(255) NOT NULL
);